services:
  db:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: jazy
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  jazy-api:
    container_name: jazy-api
    image: jazy377/jazy-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  jazy-react:
    container_name: jazy-react
    image: jazy377/jazy-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - jazy-api
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db: